### ISSUE TITLE
FieldTypeBool and SmartContract Deploy

### ISSUE THREAD

**Issue by nohkwak** [blukat29/klaytn-sdk-design#1]
https://github.com/blukat29/klaytn-sdk-design/commit/d92afa4c4410e51923a28acc32f94c6d21bf754a

When testing, the following error occurs. There seems to be a problem with the implementation of FieldTypeBool in the commit above.

Error: Missing field 'humanReadable' for 'TxTypeSmartContractDeploy' (type 40)

Also, when deploying a smart contract, calling the sendTransaction( tx ) API requires further modification so that the deploy( ) of the contract object is called.

**Comment by blukat29** [comment]
1. For the first issue (missing field), can you fiddle with this part and see if's solved: https://github.com/blukat29/klaytn-sdk-design/blob/main/src/common/field.ts#L139. Guess boolean false and undefined are not distinguished?
2. Can you be more specific with deploy issue? can you write an example code?

**Comment by nohkwak** [comment]
This issue is resolved by 180919ebcab94e6dce5d6014507338de9f0d27c8
